services:

  jenkins:

    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    user: root

    ports:
      - 8081:8080
      - 50000:50000

    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=0
      - JENKINS_HOME=/var/jenkins_home

    volumes:
      - ./jenkins:/var/jenkins/caches:/var/jenkins/caches
      - ./jenkins:/var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home:/var/jenkins_home