apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodej-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodej-app
  template:
    metadata:
      labels:
        app: nodej-app
    spec:
      containers:
      - name: my-nodej-app
        image: acrappfaluz3.azurecr.io/acrappfaluz3nodejs:5
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodej-app
    k8s-app: nodej-app
  name: nodej-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: nodej-app
