apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: acrappfaluz3.azurecr.io/acrappfaluz3:3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
    k8s-app: nodejs-app
  name: nodejs-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: nodejs-app
