apiVersion: apps/v1
kind: Deployment
metadata:
  name: appnodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appnodejs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: appnodejs
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: appnodejs
        image: myappacrfaluz.azurecr.io/server:v1
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 5002
          name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: appnodejs
spec:
  ports:
  - port: 5002
  selector:
    app: appnodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: webapp
        image: myappacrfaluz.azurecr.io/webapp:v1
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "appnodejs"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp
