version: "3.8"
services:
  
  server:
    container_name: server
    hostname: server
    build: 
     context: server
    ports:
      - "5002:5002"


  webapp:
    container_name: webapp
    hostname: webapp
    build: 
     context: ./webapp
    ports:
      - "4200:4200"
  
